DECLARE @PROD_ID VARCHAR(22);
DECLARE @CATEGORIA_CSI_ID VARCHAR(22);

DECLARE C_PRODUTOS CURSOR FOR    
SELECT
    CPRO.PROD_ID, CTGR.CSI_ID
FROM
    CSI_PRODUTO CPRO
LEFT JOIN
    PRODUTOS PROD
    ON CPRO.PROD_ID = PROD.PROD_ID
LEFT JOIN
    CSI_CATEGORIA CTGR
    ON 'GRPO'+PROD.GRPO_ID = CTGR.ID
WHERE
    ISNULL(CPRO.CATEGORIA_CSI_ID, '') <> ISNULL(CTGR.CSI_ID, '')

OPEN C_PRODUTOS;

FETCH NEXT FROM C_PRODUTOS   
INTO @PROD_ID, @CATEGORIA_CSI_ID

WHILE @@FETCH_STATUS = 0  
BEGIN 
    UPDATE
        CSI_PRODUTO
    SET
        CATEGORIA_CSI_ID = @CATEGORIA_CSI_ID
    WHERE
        PROD_ID = @PROD_ID
    
    FETCH NEXT FROM C_PRODUTOS   
    INTO @PROD_ID, @CATEGORIA_CSI_ID
END   
CLOSE C_PRODUTOS;  
DEALLOCATE C_PRODUTOS;