SELECT
	PROD_CODIGO AS 'erpId',
	FILTER_NAME as 'name',
	FILTER_VALUE as 'values'
FROM (
	SELECT
		PROD.PROD_CODIGO, FILTER_NAME = 'Altura', EQVL.EQVL_NOME AS FILTER_VALUE
	FROM
	    CSI_PRODUTO CPRD
	INNER JOIN
		PRODUTOS PROD
		ON CPRD.PROD_ID = PROD.PROD_ID
	LEFT JOIN
		EQUIVALENTES EQVL
		ON PROD.EQVL_ID = EQVL.EQVL_ID
	WHERE
		PROD.GRPO_ID = '000980020000000006'
	
	UNION ALL
	
	SELECT
		PROD.PROD_CODIGO, FILTER_NAME = 'Largura', SBCL.SBCL_NOME AS FILTER_VALUE
	FROM
	    CSI_PRODUTO CPRD
	INNER JOIN
		PRODUTOS PROD
		ON CPRD.PROD_ID = PROD.PROD_ID
	LEFT JOIN
		SUBCLASSES SBCL
		ON PROD.SBCL_ID = SBCL.SBCL_ID
	WHERE
		PROD.GRPO_ID = '000980020000000006'
	
	UNION ALL
	
	SELECT
		PROD.PROD_CODIGO, FILTER_NAME = 'Aro', REPLACE(CLSS.CLSS_NOME,'ARO ','R') AS FILTER_VALUE
	FROM
		CSI_PRODUTO CPRD
	INNER JOIN
		PRODUTOS PROD
		ON CPRD.PROD_ID = PROD.PROD_ID
	LEFT JOIN
		CLASSES CLSS
		ON PROD.CLSS_ID = CLSS.CLSS_ID
	WHERE
		PROD.GRPO_ID = '000980020000000006'
	
	UNION ALL
	
	SELECT
		PROD.PROD_CODIGO, FILTER_NAME = 'Marca', MARC.MARC_NOME AS FILTER_VALUE
	FROM
		CSI_PRODUTO CPRD
	INNER JOIN
		PRODUTOS PROD
		ON CPRD.PROD_ID = PROD.PROD_ID
	LEFT JOIN
		MARCAS MARC
		ON PROD.MARC_ID = MARC.MARC_ID
	WHERE
		PROD.GRPO_ID = '000980020000000006'
) FILTROS
