SELECT
    CPRD.PROD_CODIGO as 'erpId',
    CPRD.CSI_ID as 'id',
	MARC.MARC_NOME as 'brand'
FROM
    CSI_PRODUTO CPRD
LEFT JOIN
	PRODUTOS PROD
	ON CPRD.PROD_ID = PROD.PROD_ID
LEFT JOIN
	MARCAS MARC
	ON PROD.MARC_ID = MARC.MARC_ID